#
# ====================================================
#        SIMPLE TURBOFAN CYCLE PERFORMANCE MODEL
# ====================================================

# BUGS and ERRORS
# static pressure is incorrect for start fluid node, possibly all flow stations
# can't have zero cooling flow taken from a compressor
# python's formatted output doesn't work with RealT
# maps have to be placed in the model and can't be reused or imported in scope

import time
import os

start_time  = time.time()

exec( open( "pop.std").read())

loadDirectory( "../pop" )
loadDirectory( "../Brayton" )

exec( open( "temp.include").read())
import varsg
#varsg.out = open( "pop.out", "a")
T_TP = [ 300., 350., 400., 450., 500., 550., 600., 650., 700., 750., 800., 850., 900., 950., 1000., 1050., 1100., 1150., 1200., 1250., 1300., 1350., 1400., 1450., 1500., 1550., 1600., 1650., 1700., 1750., 1800., 1850., 1900., 1950., 2000., 2050., 2100., 2150., 2200., 2250., 2300., 2350., 2400., 2450., 2500., 2550., 2600., 2650., 2700., 2750., 2800., 2850., 2900., 2950., 3000., 3050., 3100., 3150., 3200., 3250., 3300., 3350., 3400., 3450., 3500., 3550., 3600., 3650., 3700., 3750., 3800., 3850., 3900., 3950.]
P_TP = [1., 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9, 10., 10.1, 20.1, 30.1, 40.1, 50.1, 60.1, 70.1, 80.1, 90.1, 100.1, 150.1, 200.1, 250.1, 300.1, 350.1, 400.1, 450.1, 500.1, 550.1, 600.1, 650.1, 700.1, 750.1, 800.1, 850.1, 900.1, 950.1]
FAR_TP = [0., 0.0025, 0.005, 0.0075, 0.01, 0.0125, 0.015, 0.0175, 0.02, 0.0225, 0.025, 0.0275, 0.03, 0.0325, 0.035, 0.0375, 0.04, 0.0425, 0.045, 0.0475, 0.05, .0525, .055, .0575, .06, .0625, .065 ]

#T_TP = [ 300., 400., 500. ]
#P_TP = [ 100., 200., 300. ]
#FAR_TP = [ 0., .025, .05 ]

s=[]
s1=[]
s2= []
h=[]
h1=[]
h2=[]
rho=[]
rho1=[]
rho2=[]
R=[]
R1=[]
R2=[]
gamma=[]
gam1=[]
gam2=[]
Cp=[]
Cp1=[]
Cp2=[]

FN = FN( 0 )

FN.comp.set( "CanteraFN" )
for FAR in FAR_TP:
	for P in P_TP:
		for T in T_TP:
			FN.FAR.set( FAR )
			FN.set_tp( T, float( P ) )
			s.append( FN.s.v )
			h.append( FN.ht.v )
			rho.append( FN.rhot.v )
			R.append( FN.Rt.v )
			gamma.append( FN.gamt.v )
			Cp.append( FN.Cpt.v )
		h1.append( h )
		h=[]
		s1.append( s )
		s=[]
		rho1.append( rho )
		rho=[]
		R1.append( R )
		R=[]
		gam1.append( gamma )
		gamma=[]
		Cp1.append( Cp )
		Cp=[]
	h2.append( h1 )
	h1=[]
	s2.append( s1 )
	s1=[]
	rho2.append( rho1 )
	rho1=[]
	R2.append( R1 )
	R1=[]
	gam2.append( gam1 )
	gam1=[]
	Cp2.append( Cp1 )
	Cp1=[]



f = open("table.data", "w")

print( "    T_TP = ", T_TP, file=f )
print( "    P_TP = ", P_TP, file=f )
print( "    FAR_TP = ", FAR_TP, file=f )
print( "    h_TPt = ", h2,file=f )
print( "    s_TPt = ", s2, file=f )
print( "    rho_TPt = ", rho2, file=f )
print( "    R_TPt = ", R2, file=f )
print( "    gam_TPt = ", gam2, file=f )
print( "    Cp_TPt = ", Cp2, file=f )

f.close()

os.system( "type table.top table.data table.bottom > Newtherm.py" )
